name: Deploy
on:
  push:
    branches: [nexus]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.OUTILS_HOST }}
          username: root
          key: ${{ secrets.OUTILS_SSH_KEY }}
          key_format: openssh
          script: |
            cd outils
            git pull orgin nexus
            docker compose down
            docker compose up -d --build
